---
version: "3"

services:
  node:
    image: "docker.io/node:${NODE_VERSION}"
    working_dir: /app
    volumes:
      - ${PWD}:/app:z
  api:
    build:
      context: .
      args:
        NODE_VERSION: "${NODE_VERSION}"
        APP_VERSION: "${APP_VERSION}"
        COMMIT_SHA: "${COMMIT_SHA}"
    ports:
      - '3000:3000'
