---
apiVersion: v1
kind: Service
metadata:
  name: testapi-service
  namespace: technical-test
spec:
  type: LoadBalancer
  selector:
    app: testapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
